[package]
name = "book_exercises"
version = "0.1.0"
edition = "2021"
authors = ["Ryo Light"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
